export type Property = {
  [key: string]: unknown;
  property_code: string;
  name: string;
  url: string;
  region: string;
  county: string;
  location_town: string;
  location_full: string;
  latitude: number;
  longitude: number;
  search_rank: number;
  sleeps: number;
  bedrooms: number;
  bathrooms: number;
  price_gbp: number;
  was_price_gbp: number | null;
  discount_gbp: number | null;
  price_per_person_gbp: number;
  security_deposit_gbp: number | null;
  available_start_date: string;
  rating_avg: number | null;
  review_count: number | null;
  hot_tub_privacy: string;
  single_beds: number | null;
  own_beds: number;
  own_beds_estimated: boolean;
  bed_capacity: number | null;
  zip_link_beds: number | null;
  bunk_beds: number | null;
  double_beds: number | null;
  nearest_rail_name: string;
  nearest_rail_distance_km: number | null;
  nearest_rail_lat: number | null;
  nearest_rail_long: number | null;
  nearest_bus_name: string;
  nearest_bus_distance_km: number | null;
  nearest_bus_lat: number | null;
  nearest_bus_long: number | null;
  drive_manchester_min: number | null;
  drive_manchester_km: number | null;
  drive_london_min: number | null;
  drive_london_km: number | null;
  nearest_shop_name: string | null;
  nearest_shop_brand: string | null;
  nearest_shop_lat: number | null;
  nearest_shop_long: number | null;
  nearest_shop_distance_km: number | null;
  nearest_shop_drive_km: number | null;
  nearest_shop_drive_min: number | null;
  image_urls: string[];
  image_captions: string[];
  features_all: string[];
  usps: string[];
  whats_included: string[];
  bedroom_cards: { number: number; description: string }[];
  reviews: { score: number; comment: string; date: string }[];
  long_description: string;
  short_description: string;
  room_layout: string;
  check_in_time: string;
  check_out_time: string;
  awards: string;
  score_cleanliness: number | null;
  score_location: number | null;
  score_comfort_equipment: number | null;
  score_value_for_money: number | null;
  score_local_amenities: number | null;
};
export type Filters = {
  priceMin: number;
  priceMax: number;
  bedrooms: number;
  bathrooms: number;
  ownBeds: number;
  privateHotTub: boolean;
  railKm: number;
  busKm: number;
  amenities: string[];
  favourite: boolean;
  minRating: number;
  minCleanliness: number;
  levelAccess: boolean;
  groundFloor: boolean;
  wheelchair: boolean;
  pets: boolean;
  keyword: string;
};
export type Search = {
  where: string;
  startMin: string;
  startMax: string;
  guests: number;
  everyoneBed: boolean;
  category: string;
  sort: string;
  filters: Filters;
  view: "list" | "map";
};
export type Store = { recent: string[] };
